#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
iau2000a_to_header.py
=====================
将 IERS 官方 IAU 2000A 章动黄经表 (Table 5.3a) 转换为
libsxwnl 项目使用的 C++ 数组格式.

数据源:
    https://iers-conventions.obspm.fr/content/chapter5/additional_info/tab5.3a.txt

表结构:
    表内分两段:
      j = 0  : 1320 项 (与 t 无关的常数振幅)
      j = 1  :   38 项 (与 t 一次方成比例)
    每行 17 列:
      i A_i A"_i  N_l N_l' N_F N_D N_Om N_LMe N_LVe N_LE N_LMa N_LJ N_LSa N_LU N_LNe N_pA
    其中:
      A_i    : 正弦项振幅 (单位: microarcsec, 简记 μas)
      A"_i   : 余弦项振幅 (单位: μas)
      N_x    : 14 个基本参数 (Delaunay 5 + 8 行星平黄经 + 岁差 p_A) 的整数乘子

章动计算公式 (IERS Conv 2010 §5.5, eq 35):
    ΔΨ(t) = Σ_j t^j · Σ_i [ A_i(j)·sin(ARG_i)  +  A"_i(j)·cos(ARG_i) ]
    ARG_i = N_i,1·l + N_i,2·l' + N_i,3·F + N_i,4·D + N_i,5·Ω
           + N_i,6·L_Me + ... + N_i,13·L_Ne + N_i,14·p_A

输出结构:
    数组 NUT_LON_HP_J0[] : 1320 × (2 + 14) = 1320 × 16 长整型
      每 16 个元素为一项: [A_μas, A"_μas, N_l, N_l', N_F, N_D, N_Om,
                        N_LMe, N_LVe, N_LE, N_LMa, N_LJ, N_LSa, N_LU, N_LNe, N_pA]
    数组 NUT_LON_HP_J1[] : 38 × 16 同样布局

用法:
    python3 iau2000a_to_header.py <tab5.3a.txt> <output.h>
"""
import sys
import re
from pathlib import Path


NUM_ARGS = 14  # 5 Delaunay + 8 planetary + 1 precession
COLS_PER_TERM = 2 + NUM_ARGS  # 振幅×2 + 14 个乘子


def parse_iers_table(path: Path):
    """
    读取 tab5.3a.txt, 返回 { 0: [...项...], 1: [...项...] } 两段.
    每项是 tuple: (A, A_pp, N_l, N_lp, N_F, N_D, N_Om,
                   N_Me, N_Ve, N_E, N_Ma, N_J, N_Sa, N_U, N_Ne, N_pA)
    """
    sections = {0: [], 1: []}
    current = None
    j_header = re.compile(r"^\s*j\s*=\s*(\d+)\s+Number of terms")

    with open(path, "r", encoding="ascii") as fp:
        for line in fp:
            m = j_header.match(line)
            if m:
                current = int(m.group(1))
                continue
            if current is None:
                continue
            parts = line.split()
            # 有效数据行至少 17 列: i + A + A" + 14 个整数乘子
            if len(parts) < 3 + NUM_ARGS:
                continue
            # 首列必须是整数序号
            if not parts[0].lstrip("-").isdigit():
                continue
            try:
                # A, A_pp 是浮点 (含小数, 单位 μas)
                A = float(parts[1])
                A_pp = float(parts[2])
                # 后 14 列是整数 (可负)
                Ns = [int(x) for x in parts[3 : 3 + NUM_ARGS]]
            except ValueError:
                continue
            sections[current].append((A, A_pp) + tuple(Ns))
    return sections


def render_header(sections, output_path: Path):
    j0 = sections[0]
    j1 = sections[1]

    lines = []
    lines.append("// Auto-generated by tools/iau2000a_to_header.py -- DO NOT EDIT MANUALLY")
    lines.append(
        "// SOURCE: IERS Conventions 2010 Ch.5 Table 5.3a (章动黄经, IAU 2000A_R06)"
    )
    lines.append("// URL: https://iers-conventions.obspm.fr/content/chapter5/additional_info/tab5.3a.txt")
    lines.append("//")
    lines.append(f"// j = 0 段: {len(j0)} 项 (常数振幅)")
    lines.append(f"// j = 1 段: {len(j1)} 项 (与 t 一次方成比例)")
    lines.append("//")
    lines.append("// 布局: 每项 16 个 long, 依次是")
    lines.append("//   [ A_uas, App_uas,      // 单位 microarcsec")
    lines.append("//     N_l, N_lp, N_F, N_D, N_Om,")
    lines.append("//     N_LMe, N_LVe, N_LE, N_LMa, N_LJ, N_LSa, N_LU, N_LNe,")
    lines.append("//     N_pA ]")
    lines.append("//")
    lines.append("// 注: A_uas / App_uas 为浮点 μas, 使用 long double 存放以保留精度")
    lines.append("#pragma once")
    lines.append("")
    lines.append("namespace sxwnl_hp {")
    lines.append("")
    lines.append(f"static constexpr int NUT_LON_HP_J0_COUNT = {len(j0)};")
    lines.append(f"static constexpr int NUT_LON_HP_J1_COUNT = {len(j1)};")
    lines.append(f"static constexpr int NUT_LON_HP_COLS = {COLS_PER_TERM};")
    lines.append("")

    def emit_array(name, rows):
        lines.append(f"static constexpr long double {name}[{len(rows)} * {COLS_PER_TERM}] = {{")
        for A, App, *Ns in rows:
            row_parts = [f"{A:.6f}L", f"{App:.6f}L"] + [str(n) for n in Ns]
            lines.append("\t" + ", ".join(row_parts) + ",")
        # 去尾逗号
        if lines[-1].endswith(","):
            lines[-1] = lines[-1][:-1]
        lines.append("};")
        lines.append("")

    emit_array("NUT_LON_HP_J0", j0)
    emit_array("NUT_LON_HP_J1", j1)

    lines.append("}  // namespace sxwnl_hp")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"生成 {output_path} (j=0: {len(j0)} 项, j=1: {len(j1)} 项)")


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    if not src.exists():
        print(f"找不到源文件: {src}", file=sys.stderr)
        sys.exit(1)
    sections = parse_iers_table(src)
    render_header(sections, dst)


if __name__ == "__main__":
    main()
