#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
vsop87d_to_header.py
====================
将 IMCCE 官方 VSOP87D 地球日心球坐标文件 (VSOP87D.ear) 转换为
libsxwnl 项目使用的 C++ 数组格式,与 src/eph_data.h 中的 XL0_0 保持结构一致。

数据源:
    ftp://ftp.imcce.fr/pub/ephem/planets/vsop87/VSOP87D.ear
    (HTTPS 镜像: https://ftp.imcce.fr/pub/ephem/planets/vsop87/VSOP87D.ear)

说明:
    项目现有 XL0_0 使用的是 VSOP87D (Date-of-epoch, 瞬时分点),
    不是 VSOP87B (J2000 固定分点). 两者主要差别在 L 分量的 T^1 项
    (VSOP87D 包含岁差项, 首项为 6283.32; VSOP87B 无岁差, 首项为 6283.08).
    为保持与现有实现兼容, HP 备件也使用 D 版, 只是把截断项恢复为全项.

VSOP87B 每行格式(固定列宽,见 vsop87.doc):
    IV IC  A1..A12   S           K           A           B           C
其中:
    IV = 版本/行星/变量代号 (e.g. 2310 = VSOP87B Earth L)
    IC = 段内序号
    A1..A12 = 基本变量的整数乘子
    S,K = 正/余弦系数
    A = sqrt(S²+K²) 振幅
    B = 相位 (弧度)
    C = 频率 (弧度/儒略千年)

输出的 XL0_0_HP 数组格式:
    [0]           A 的倍率 (10^10)
    [1..19]       位置索引表 (19 个累计偏移量, 对应 L0..L5, B0..B5, R0..R5)
    [20..]        (amp*10^10, phase, freq) 三元组序列

用法:
    python3 vsop87b_to_header.py <VSOP87B.ear> <output.h>
"""
import sys
import re
from pathlib import Path


AMP_SCALE = 10 ** 10  # 与 XL0_0 保持一致的振幅倍率
VARS = ["L", "B", "R"]  # 3 个变量: 黄经、黄纬、距离
POWERS = 6              # 每变量 6 阶时间幂 (T^0 ~ T^5)


def parse_vsop87b(path: Path):
    """
    读取 VSOP87B.ear, 返回 sections[var_idx][power_idx] = list of (A, B, C).
    """
    sections = {(v, p): [] for v in range(3) for p in range(POWERS)}
    current = None

    # 同时兼容 VSOP87B (J2000 分点) 和 VSOP87D (瞬时分点/Date-of-epoch)
    # 现有 XL0_0 使用的是 VSOP87D, 因此优先支持 D 版
    header_re = re.compile(
        r"^\s*VSOP87\s+VERSION\s+[BD]\d+\s+EARTH\s+VARIABLE\s+(\d+)\s+\(LBR\)\s+\*T\*\*(\d+)"
    )

    with open(path, "r", encoding="ascii") as fp:
        for line in fp:
            m = header_re.match(line)
            if m:
                var_idx = int(m.group(1)) - 1  # 1..3 → 0..2
                power_idx = int(m.group(2))
                assert 0 <= var_idx < 3, f"Bad var: {m.group(1)}"
                assert 0 <= power_idx < POWERS, f"Bad power: {m.group(2)}"
                current = (var_idx, power_idx)
                continue

            if current is None:
                continue

            # 数据行只需最后 3 个浮点 (A, B, C).
            # 注意 VSOP87 定长格式的整数乘子字段仅 3 列, 负数如 "-13" 会挤住
            # 前一列(见 "8-13"), 直接 split() 会误认为 18 列而非 19 列.
            # 但最后 5 个浮点字段(S,K,A,B,C)总带前导空格, 所以 rsplit 抓末 3 项即可.
            stripped = line.strip()
            if not stripped:
                continue
            tail = stripped.rsplit(maxsplit=3)
            if len(tail) < 4:
                continue
            try:
                A = float(tail[-3])
                B = float(tail[-2])
                C = float(tail[-1])
            except ValueError:
                continue

            sections[current].append((A, B, C))

    return sections


def render_header(sections, output_path: Path):
    """
    将 sections 渲染成 C++ header, 结构与 XL0_0 一致:
        [0]                       = AMP_SCALE
        [1..19]                   = 位置索引累计表 (19 个)
        [20..]                    = triples (A*AMP_SCALE 取整, B, C)

    位置索引解释 (与 src/eph.cpp 中 E_Lon() 的读取逻辑对应):
        pn = zn*6 + 1        (zn: 0=L, 1=B, 2=R)
        n1 = F[pn+i], n2 = F[pn+1+i]  给出第 i 阶时间幂的 (start,end) 偏移
    """
    # 顺序: L0..L5, B0..B5, R0..R5 -> 18 段
    ordered = [(v, p) for v in range(3) for p in range(POWERS)]

    # 从偏移量 20 开始堆放数据 (前 20 个位置留给标量+索引表)
    triples = []
    offsets = []  # 19 个数值: 每段起点 + 最后一段终点
    cursor = 20  # 首个数据项的绝对索引
    offsets.append(cursor)

    for key in ordered:
        for (A, B, C) in sections[key]:
            triples.append((A, B, C))
            cursor += 3
        offsets.append(cursor)

    # 检验: offsets 应有 19 个 (18 段 + 1 结尾)
    assert len(offsets) == 19, f"offsets 长度 {len(offsets)} != 19"

    # 生成 header
    lines = []
    lines.append("// Auto-generated by tools/vsop87d_to_header.py -- DO NOT EDIT MANUALLY")
    lines.append("// SOURCE: IMCCE VSOP87D.ear (地球日心球坐标, Date-of-epoch 瞬时分点黄道)")
    lines.append("// 与现有 src/eph_data.h 中 XL0_0 使用同一坐标系,只是恢复了截断掉的项.")
    lines.append("//")
    lines.append(
        "// 各段项数(总 {} 项, 现有 XL0_0 截断版约 890 项):".format(len(triples))
    )
    total_by_var = [0, 0, 0]
    for i, key in enumerate(ordered):
        var, pw = key
        n = len(sections[key])
        total_by_var[var] += n
        lines.append(
            "//   {}{} = {:>4d} terms".format(VARS[var], pw, n)
        )
    lines.append(
        "// 合计: L={}, B={}, R={}, TOTAL={}".format(
            total_by_var[0], total_by_var[1], total_by_var[2], sum(total_by_var)
        )
    )
    lines.append("//")
    lines.append(
        "// 声明精度: J2000 ± 4000 年 黄经 0.001\" (arc-sec), 相比截断版有约一个量级的提升."
    )
    lines.append(
        "// 单位与 src/eph_data.h XL0_0 一致: 振幅 A * 10^10 存为整数, B/C 为原始 long double."
    )
    lines.append("#pragma once")
    lines.append("")
    lines.append("namespace sxwnl_hp {")
    lines.append("")
    lines.append("static constexpr long double XL0_0_HP[] = {")

    # 首行: A_SCALE + 索引表 (19 个)
    idx_str = ", ".join(str(o) for o in offsets)
    lines.append(f"\t{AMP_SCALE},   // A 的倍率")
    lines.append(f"\t{idx_str},   // 位置索引表(19 项, 描述 L0..R5 段偏移)")

    # 分段输出 triples, 每段一行, 用注释标示段名
    line_cursor = 20
    for i, key in enumerate(ordered):
        var, pw = key
        n = len(sections[key])
        if n == 0:
            continue
        var_name = VARS[var]
        parts = []
        for (A, B, C) in sections[key]:
            amp_int = round(A * AMP_SCALE)
            parts.append(f"{amp_int}, {B:.11f}L, {C:.11f}L")
        lines.append("\t/*{}{}*/ {},".format(var_name, pw, ", ".join(parts)))
        line_cursor += n * 3

    # 去掉最后一项末尾的逗号
    if lines[-1].endswith(","):
        lines[-1] = lines[-1][:-1]
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace sxwnl_hp")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"生成 {output_path} (共 {len(triples)} 项)")


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    if not src.exists():
        print(f"找不到源文件: {src}", file=sys.stderr)
        sys.exit(1)

    sections = parse_vsop87b(src)
    render_header(sections, dst)


if __name__ == "__main__":
    main()
